49 geoquery microarray studies
reactome/gsa-backend pull request #68
Opened 2024-08-08 13:47 UTC by alexgrent

Fetching data from GEO, via Python and R within the DatasetFetchers

2024-08-13 08:00 UTC, jgriss requested changes
Hi @alexgrent !

This looks great! Only minor points we could discuss - but as you saw I'm not 100% sure myself about them.

Let me know what you think, then I'll merge everything and run the integration tests.

2024-08-13 12:37 UTC, alexgrent commented on reactome_analysis_api/reactome_analysis_api/controllers/datasets_controller.py
> +        ExternalDatasource(id="geo", name="GEO expression",
changed the id to  geo_mircroarray legacy sounds a little bit prejudice

2024-08-13 12:41 UTC, alexgrent commented
Hi changed according to review. 
I think you are right we can differentiate a little bit more to GREIN, 
changed the id and the description to be more specific to microarray data

2024-08-13 12:45 UTC, alexgrent commented
squash commits before merging

2024-08-28 21:21 UTC, jgriss approved these changes
@alexgrent Thanks a lot! Looks great!

2024-08-28 21:21 UTC, merged